source("~/Projects/Calcs/R/DSR/01 Variable Realizations.R")
print("done 01")
source("~/Projects/Calcs/R/DSR/02 Survey Analysis.r")
print("done 02")
source("~/Projects/Calcs/R/DSR/03 Conc Models.R")
print("done 03")
source("~/Projects/Calcs/R/DSR/04 Conc Lab Error.R")
print("done 04")
source("~/Projects/Calcs/R/DSR/05 River Geometry.R")
print("done 05")
source("~/Projects/Calcs/R/DSR/06 Conc Realizations-Data Setup.R")
print("done 06")
source("~/Projects/Calcs/R/DSR/07 ETref to Evap Realizations.R")
print("done 07")
source("~/Projects/Calcs/R/DSR/08 Conc Realizations.R")
print("done 08")
source("~/Projects/Calcs/R/DSR/09 Transport and Storage.R")
print("done 09")
source("~/Projects/Calcs/R/DSR/10 Water and Mass Models.R")
print("done 10")
source("~/Projects/Calcs/R/DSR/11 Water and Mass Models-A and S.R")
print("done 11")
source("~/Projects/Calcs/R/DSR/12 Water and Mass Models-Atmos.R")
print("done 12")
source("~/Projects/Calcs/R/DSR/13 Water and Mass Models-Storage.R")
print("done 13")
source("~/Projects/Calcs/R/DSR/14 Contrib Mass.R")
print("done 14")
source("~/Projects/Calcs/R/DSR/15 Contrib Water.R")
print("done 15 - done all")
