source("~/Projects/Calcs/R/USR/01 Variable Realizations.R")
print("done 01")
source("~/Projects/Calcs/R/USR/02 Survey Analysis and Plots.r")
print("done 02")
source("~/Projects/Calcs/R/USR/03 Conc Models.R")
print("done 03")
source("~/Projects/Calcs/R/USR/04 Conc Lab Error.R")
print("done 04")
source("~/Projects/Calcs/R/USR/05 River Geometry.R")
print("done 05")
source("~/Projects/Calcs/R/USR/06 Conc Realizations-Data Setup.R")
print("done 06")
source("~/Projects/Calcs/R/USR/07 ETref to Evap Realizations.R")
print("done 07")
source("~/Projects/Calcs/R/USR/08 Conc Realizations.R")
print("done 08")
source("~/Projects/Calcs/R/USR/09 Transport and Storage.R")
print("done 09")
source("~/Projects/Calcs/R/USR/10 Water and Mass Models.R")
print("done 10")
source("~/Projects/Calcs/R/USR/11 Water and Mass Models-A and S.R")
print("done 11")
source("~/Projects/Calcs/R/USR/12 Water and Mass Models-Atmos.R")
print("done 12")
source("~/Projects/Calcs/R/USR/13 Water and Mass Models-Storage.R")
print("done 13")
source("~/Projects/Calcs/R/USR/14 Contrib Mass.R")
print("done 14")
source("~/Projects/Calcs/R/USR/15 Contrib Water.R")
print("done 15 - Done all")