setwd("~/Projects/Calcs/USR/Models/Stochastic/")
x <- load("widthA1.Rdata")
w1 <- get(x)
x <- load("widthB1.Rdata")
w2 <- get(x)
x <- load("widthC1.Rdata")
w3 <- get(x)
x <- load("widthD1.Rdata")
w4 <- get(x)
x <- load("widthE1.Rdata")
w5 <- get(x)
rm(list=x)
wAll <- cbind(w1,w2,w3,w4,w5)
wavg <- rowMeans(wAll, na.rm=TRUE)
mean(wavg, na.rm=TRUE)


setwd("~/Projects/Calcs/DSR/Models/Stochastic/")
x <- load("widthF1.Rdata")
w1 <- get(x)
x <- load("widthG1.Rdata")
w2 <- get(x)
rm(list=x)
wAll <- cbind(w1,w2)
wavg <- rowMeans(wAll, na.rm=TRUE)
mean(wavg, na.rm=TRUE)